language: node_js
node_js:
  - "6"
  - "8"
  - "10"

install:
  - npm config set spin=false
  - npm install -g coveralls
  - npm install
  - npm install graphql@$GRAPHQL_VERSION

script:
  - npm test
  - npm run lint
  - npm run coverage
  - coveralls < ./coverage/lcov.info || true # if coveralls doesn't have it covered

# Allow Travis tests to run in containers.
sudo: false

env:
  - GRAPHQL_VERSION='^14.0'
