[build]
  base    = "docs/"
  publish = "docs/public/"
  command = "gatsby build --prefix-paths && mkdir -p docs/graphql-tools && mv public/* docs/graphql-tools && mv docs public/ && mv public/docs/graphql-tools/_redirects public"
[build.environment]
  NPM_VERSION = "6"
